-- Mise à jour noms et emojis pour tous les tickers existants

UPDATE isin_utilisateurs SET nom='S&P 500', emoji='📈' WHERE ticker='^GSPC';
UPDATE isin_utilisateurs SET nom='Amundi NASDAQ-100 ETF', emoji='📈' WHERE ticker='PANX.PA';
UPDATE isin_utilisateurs SET nom='Amundi MSCI World Swap ETF', emoji='🌍' WHERE ticker='CW8.PA';
UPDATE isin_utilisateurs SET nom='Amundi PEA Émergents ETF', emoji='🌍' WHERE ticker='PAEEM.PA';
UPDATE isin_utilisateurs SET nom='Amundi PEA Nasdaq-100 ETF', emoji='📈' WHERE ticker='PUST.PA';
UPDATE isin_utilisateurs SET nom='Amundi PEA S&P 500 ETF', emoji='📈' WHERE ticker='PSP5.PA';
UPDATE isin_utilisateurs SET nom='ASML', emoji='🔬' WHERE ticker='ASML';
UPDATE isin_utilisateurs SET nom='STMicroelectronics', emoji='🔧' WHERE ticker='STMPA.PA';
UPDATE isin_utilisateurs SET nom='Infineon', emoji='💡' WHERE ticker='IFX.DE';
UPDATE isin_utilisateurs SET nom='Newron Pharmaceuticals', emoji='🧬' WHERE ticker='NP5.DE';
UPDATE isin_utilisateurs SET nom='EchoStar', emoji='🛰️' WHERE ticker='SATS';
UPDATE isin_utilisateurs SET nom='Dropbox', emoji='☁️' WHERE ticker='DBX';
UPDATE isin_utilisateurs SET nom='Coinbase', emoji='₿' WHERE ticker='COIN';
UPDATE isin_utilisateurs SET nom='PayPal', emoji='💳' WHERE ticker='PYPL';
UPDATE isin_utilisateurs SET nom='Zoom', emoji='🎥' WHERE ticker='ZM';
UPDATE isin_utilisateurs SET nom='Microsoft', emoji='🖥️' WHERE ticker='MSFT';
UPDATE isin_utilisateurs SET nom='Apple', emoji='📱' WHERE ticker='AAPL';
UPDATE isin_utilisateurs SET nom='Tesla', emoji='🚗' WHERE ticker='TSLA';
UPDATE isin_utilisateurs SET nom='Netflix', emoji='🎬' WHERE ticker='NFLX';
UPDATE isin_utilisateurs SET nom='Amazon', emoji='📦' WHERE ticker='AMZN';
UPDATE isin_utilisateurs SET nom='Samsung', emoji='📱' WHERE ticker='005930.KS';
UPDATE isin_utilisateurs SET nom='NextEra Energy', emoji='⚡' WHERE ticker='NEE';
UPDATE isin_utilisateurs SET nom='TSMC', emoji='🔧' WHERE ticker='TSM';
UPDATE isin_utilisateurs SET nom='Seagate', emoji='💾' WHERE ticker='STX';
UPDATE isin_utilisateurs SET nom='Micron Technology', emoji='💾' WHERE ticker='MU';
UPDATE isin_utilisateurs SET nom='Eiffage', emoji='🏗️' WHERE ticker='FGR.PA';
UPDATE isin_utilisateurs SET nom='Soitec', emoji='⚡' WHERE ticker='SOI.PA';
UPDATE isin_utilisateurs SET nom='Amundi PEA MSCI Europe ETF', emoji='🇪🇺' WHERE ticker='PCEU.PA';
UPDATE isin_utilisateurs SET nom='Dassault Systèmes', emoji='💻' WHERE ticker='DSY.PA';
UPDATE isin_utilisateurs SET nom='iShares MSCI World PEA ETF', emoji='🌍' WHERE ticker='WPEA.PA';
UPDATE isin_utilisateurs SET nom='Amundi EURO STOXX 50 ETF', emoji='🇪🇺' WHERE ticker='C50.PA';
UPDATE isin_utilisateurs SET nom='Amundi PEA Asie Émergente ETF', emoji='🌏' WHERE ticker='PAASI.PA';
UPDATE isin_utilisateurs SET nom='Veolia Environnement', emoji='♻️' WHERE ticker='VIE.PA';
UPDATE isin_utilisateurs SET nom='Amundi Semiconductors ETF', emoji='🔬' WHERE ticker='CHIP.PA';
UPDATE isin_utilisateurs SET nom='Dassault Aviation', emoji='✈️' WHERE ticker='AM.PA';
UPDATE isin_utilisateurs SET nom='Bayer', emoji='💊' WHERE ticker='BAYN.DE';
UPDATE isin_utilisateurs SET nom='Deezer', emoji='🎵' WHERE ticker='DEEZR.PA';
UPDATE isin_utilisateurs SET nom='Lerøy Seafood', emoji='🐟' WHERE ticker='LSG.OL';
UPDATE isin_utilisateurs SET nom='Forsee Power', emoji='🔋' WHERE ticker='FORSE.PA';
UPDATE isin_utilisateurs SET nom='Safran', emoji='✈️' WHERE ticker='SAF.PA';
UPDATE isin_utilisateurs SET nom='Airbus', emoji='✈️' WHERE ticker='AIR';
UPDATE isin_utilisateurs SET nom='Defence ETF', emoji='🛡️' WHERE ticker='DFNS';
UPDATE isin_utilisateurs SET nom='Ryanair', emoji='✈️' WHERE ticker='RYAAY';
UPDATE isin_utilisateurs SET nom='NVIDIA', emoji='🎮' WHERE ticker='NVDA';
UPDATE isin_utilisateurs SET nom='Alphabet', emoji='🔍' WHERE ticker='GOOGL';
UPDATE isin_utilisateurs SET nom='AI & Big Data ETF', emoji='🤖' WHERE ticker='AIBD';
UPDATE isin_utilisateurs SET nom='Cameco', emoji='☢️' WHERE ticker='CCJ';
UPDATE isin_utilisateurs SET nom='Broadcom', emoji='📡' WHERE ticker='AVGO';
UPDATE isin_utilisateurs SET nom='Vistra', emoji='⚡' WHERE ticker='VST';
UPDATE isin_utilisateurs SET nom='Visa', emoji='💳' WHERE ticker='V';
UPDATE isin_utilisateurs SET nom='AMD', emoji='🖥️' WHERE ticker='AMD';
UPDATE isin_utilisateurs SET nom='Atlas Lithium', emoji='🔋' WHERE ticker='ATLX';
UPDATE isin_utilisateurs SET nom='Paladin Energy', emoji='☢️' WHERE ticker='PDN.AX';
UPDATE isin_utilisateurs SET nom='Rheinmetall', emoji='🛡️' WHERE ticker='RHM.DE';
UPDATE isin_utilisateurs SET nom='Cloudflare', emoji='☁️' WHERE ticker='NET';
UPDATE isin_utilisateurs SET nom='Regeneron', emoji='💊' WHERE ticker='REGN';
UPDATE isin_utilisateurs SET nom='Fresenius', emoji='🏥' WHERE ticker='FRE.DE';
UPDATE isin_utilisateurs SET nom='Stride Inc', emoji='🎓' WHERE ticker='LRN';
UPDATE isin_utilisateurs SET nom='Palantir', emoji='🛡️' WHERE ticker='PLTR';
UPDATE isin_utilisateurs SET nom='Abivax', emoji='💉' WHERE ticker='ABVX';
UPDATE isin_utilisateurs SET nom='Meta', emoji='📘' WHERE ticker='META';
UPDATE isin_utilisateurs SET nom='Alamos Gold', emoji='⛏️' WHERE ticker='AGI';
